### PR TITLE
Fix #73 and support immutable dates

### LINKED ISSUE #73: nextOpen() and nextClose() don't return the correct values when called simultaneously
Hello,

The following test does not pass :

```php
public function testItReturnsNextOpenAndNextClose()
{
    $mondayAfternoon = new \DateTime('2018-10-15 15:00'); // monday 15:00

    $openingHours = OpeningHours::create(['monday' => ['14:00-18:00'], 'tuesday' => ['09:00-12:00']]);

    $this->assertEquals(new \DateTime('2018-10-16 09:00'), $openingHours->nextOpen($mondayAfternoon));
    $this->assertEquals(new \DateTime('2018-10-15 18:00'), $openingHours->nextClose($mondayAfternoon));
}
```

DateTime `$mondayAfternoon` is modified when passed to `nextOpen()` and `nextClose()` methods. After the first assertion, `$mondayAfternoon` value is the same as `nextOpen()` return.

The problem persists even when I replace `$mondayAfternoon` param by a clone.

`$mondayAfternoon` is not modified anymore, but `nextClose()` will return a result based on a previous `nextXXX()` call.

The following test

```php
public function testItReturnsNextCloseTwiceInARow()
{
    $mondayAfternoon = new \DateTime('2018-10-15 15:00'); // monday 15:00

    $openingHours = OpeningHours::create(['monday' => ['14:00-18:00'], 'tuesday' => ['09:00-12:00']]);

    $this->assertEquals(new \DateTime('2018-10-15 18:00'), $openingHours->nextClose(clone $mondayAfternoon)); // OK
    $this->assertEquals(new \DateTime('2018-10-15 18:00'), $openingHours->nextClose(clone $mondayAfternoon)); // NOT OK
}
```

fails with the following message

> Failed asserting that two DateTime objects are equal.
> --- Expected
> +++ Actual
> @@ @@
> -2018-10-15T18:00:00.000000+0000
> +2018-10-16T12:00:00.000000+0000

Finally I cannot pass a `new DateTimeImmutable` object to `nextOpen()` and `nextClose()` methods (even their signatures accept `DateTimeInterface`) because of the return type hint (`DateTime`) but it may be another ticket.

### PR DESCRIPTION
**Pull request by kylekatarnls**
- Allow DateTimeImmutable
- Fix #73: do not modify the passed datetime
- Allow multiple calls for nextClose/nextOpen

### CODE REVIEW

File: src/OpeningHours.php [hunk 1]
```diff
@@ -150,13 +151,17 @@ public function isClosed(): bool
         return $this->isClosedAt(new DateTime());
     }
 
-    public function nextOpen(DateTimeInterface $dateTime): DateTime
+    public function nextOpen(DateTimeInterface $dateTime): DateTimeInterface
```
Comment (freekmurze) [inline src/OpeningHours.php]: Unfortunately changing the return type is a breaking change.

**Comment by freekmurze** [comment]
Closing this as changing the return type is a breaking change. We'll revisit this when creating a new major version of the package.

**Comment by kylekatarnls** [comment]
Nop because your PHP requirement: `php: ^7.0` implies that any `DateTime` object implements `DateTimeInterface`, so unless using reflexion, there is no break, but with reflexion, anything is breaking change.

So you should not consider it as a breaking change and could safely implement this in the current major version.

**Comment by kylekatarnls** [comment]
Then you still have the missing `reset($timeRange);`, this bug should be fixed in the current version.

File: src/OpeningHours.php (hunk 1 above)
Comment (kylekatarnls) [reply src/OpeningHours.php]: Nop because your PHP requirement: `php: ^7.0` implies that any `DateTime` object implements `DateTimeInterface`, so unless using reflexion, there is no break, but with reflexion, anything is breaking change.

File: .gitignore [hunk 2]
```diff
@@ -2,3 +2,4 @@ build
 composer.lock
 docs
 vendor
+.idea
```
[the remark this answers is not in the document]
Comment (kylekatarnls) [reply .gitignore]: Cleaned, it will disappear if you re-open the PR.

**Comment by freekmurze** [comment]
It is a breaking change.

Consider this code:

```
	class A
	{
		public function date(): DateTime{
			return new DateTime();
		}
	}
	
	class B extends A
	{
		public function date(): DateTime{
			return new DateTime();
		}
	}

        (new B)->date()
```

If you change the return type of class A to `DateTimeInterface` you'll get an error:

```
Declaration of B::date(): DateTime must be compatible with A::date(): DateTimeInterface
```

**Comment by kylekatarnls** [comment]
Still, this could have been done differently, simply closing this PR rather than asking for modifications (or take it partially to get the bug fixes, or tag it to be merged in next major version) seem very counter-productive to me. I recommend you a more encouraging contributing process for your PRs such as discuss first, propose alternatives, then decide when every participant has finished to consider possible solutions.

**Comment by freekmurze** [comment]
Thank you for your work around this. I'm sorry that my comments seems counter-productive to you. 

Feel free to either rework this PR (in that case I'll reopen it when you push changes) or submit a new PR altogether.
