### PR TITLE
Fix next methods

### LINKED ISSUE #73: nextOpen() and nextClose() don't return the correct values when called simultaneously
Hello,

The following test does not pass :

```php
public function testItReturnsNextOpenAndNextClose()
{
    $mondayAfternoon = new \DateTime('2018-10-15 15:00'); // monday 15:00

    $openingHours = OpeningHours::create(['monday' => ['14:00-18:00'], 'tuesday' => ['09:00-12:00']]);

    $this->assertEquals(new \DateTime('2018-10-16 09:00'), $openingHours->nextOpen($mondayAfternoon));
    $this->assertEquals(new \DateTime('2018-10-15 18:00'), $openingHours->nextClose($mondayAfternoon));
}
```

DateTime `$mondayAfternoon` is modified when passed to `nextOpen()` and `nextClose()` methods. After the first assertion, `$mondayAfternoon` value is the same as `nextOpen()` return.

The problem persists even when I replace `$mondayAfternoon` param by a clone.

`$mondayAfternoon` is not modified anymore, but `nextClose()` will return a result based on a previous `nextXXX()` call.

The following test

```php
public function testItReturnsNextCloseTwiceInARow()
{
    $mondayAfternoon = new \DateTime('2018-10-15 15:00'); // monday 15:00

    $openingHours = OpeningHours::create(['monday' => ['14:00-18:00'], 'tuesday' => ['09:00-12:00']]);

    $this->assertEquals(new \DateTime('2018-10-15 18:00'), $openingHours->nextClose(clone $mondayAfternoon)); // OK
    $this->assertEquals(new \DateTime('2018-10-15 18:00'), $openingHours->nextClose(clone $mondayAfternoon)); // NOT OK
}
```

fails with the following message

> Failed asserting that two DateTime objects are equal.
> --- Expected
> +++ Actual
> @@ @@
> -2018-10-15T18:00:00.000000+0000
> +2018-10-16T12:00:00.000000+0000

Finally I cannot pass a `new DateTimeImmutable` object to `nextOpen()` and `nextClose()` methods (even their signatures accept `DateTimeInterface`) because of the return type hint (`DateTime`) but it may be another ticket.

### PR DESCRIPTION
**Pull request by kylekatarnls**
- Allow DateTimeImmutable where it's possible
- Fix #73: do not modify the passed datetime
- Allow multiple calls for nextClose/nextOpen
- Add unit tests and incomplete tests to show the current and ongoing support of immutability

### CODE REVIEW

**Comment by kylekatarnls** [comment]
Of course, TODOs and incomplete tests are not required, but I think it's quite a good way to prepare sort of a wish list for a v2.

File: src/OpeningHours.php [hunk 1]
```diff
@@ -150,13 +151,20 @@ public function isClosed(): bool
         return $this->isClosedAt(new DateTime());
     }
 
+    /**
+     * @TODO This should return DateTimeInterface on next major release
```
Comment (Jamesking56) [inline src/OpeningHours.php]: `@TODO` should be lowercase to meet the PHPDoc spec: http://docs.phpdoc.org/references/phpdoc/tags/todo.html

Please fix both of these

File: tests/TimeTest.php [hunk 2]
```diff
@@ -112,4 +117,15 @@ public function it_should_not_mutate_passed_datetime()
         $this->assertEquals('2016-09-27 15:00:00', $time->toDateTime($dateTime)->format('Y-m-d H:i:s'));
         $this->assertEquals('2016-09-27 12:00:00', $dateTime->format('Y-m-d H:i:s'));
     }
+
+    /** @test */
+    public function it_should_not_mutate_passed_datetime_immutable()
+    {
+        $this->markTestIncomplete('Not supported in v1.x');
```
Comment (Jamesking56) [inline tests/TimeTest.php]: Whats the reason for adding incompatible tests?

Comment (kylekatarnls) [reply tests/TimeTest.php]: As explained above, it shows explicitly the ongoing support of immutability. Document known limitations is a good practice.

File: src/Time.php [hunk 3]
```diff
@@ -83,9 +84,16 @@ public function diff(self $time): \DateInterval
         return $this->toDateTime()->diff($time->toDateTime());
     }
 
+    /**
+     * @todo This should take and return DateTimeInterface on next major release
```
Comment (Jamesking56) [inline src/Time.php]: Can I ask what the rationale is for waiting until the next release? `DateTimeInterface` should have many of the public methods that `DateTime` and `DateTimeImmutable` have, so it shouldn't be a breaking change.

Comment (kylekatarnls) [reply src/Time.php]: This decision is not mine: https://github.com/spatie/opening-hours/pull/75#issuecomment-435896626

But I agree the risk of breaking some people workflows by changing the typing (due to PHP compatibility checks) is a bit high. So it seems fair to wait for next major version, it better respects Semantic Versioning.

**Comment by freekmurze** [comment]
Thanks for your work on this. We're not going to do a v2 for this package. Feel free to fork our code an publish a package of your own with your desired features. We'll be more than happy to put a link to your repo in our readme.

**Comment by kylekatarnls** [comment]
But this PR is valid for v1 (fix the bug #73 with no breaking change) and I see you're looking for new maintainer #77

So why not keep this open for `1.9.0`?

I would agree to fork the project, but it seems really more appropriate to me that spatie would keep the ownership and just add maintainers in this project. I do not feel confortable about a forks competition. I would prefer a more centralized solution and would avoid using a divergente version from other people.

Did you plan to mark this package as abandoned no matter what? Or only if you don't find maintainers willing to stay on spatie/opening-hours?
